### ISSUE TITLE
python 2.7 changes

### ISSUE THREAD

**Issue by amirmohsen-am** [brandon-rhodes/pycon2010-mighty-dictionary#1]
when i try to run _dictdraw.py (or any other file that uses _dictdraw) i get this error:
`File "_dictinfo.py", line 85, in <module>
    dummy = dictobject(d).ma_table[0].me_key`
`ValueError: NULL pointer access`

i'm using windows and python 2.7.

i think this problem is because the internals of dictionaries has changed from version 2.6 to 2.7.

is there any way to fix this?

**Comment by brandon-rhodes** [comment]
Interesting! I was not aware that the dictionary internals had changed. To adapt the code for Python 2.7, if it is indeed 2.7 that changed, the `struct` statements in the C code would need to be studied and the changes written into the dictdraw code.

Alternatively, the difference could be that Windows lays memory out differently in a way that the code does not expect.

Or it could be that my code was 32-bit specific but you are on a 64-bit system!

I myself probably won't have time to look at this within the next few months, since this repository exists mainly to archive the state of things back in 2010 when I gave the talk and I have other projects that need my attention right now, but if you wind up discovering the answer then I certainly wouldn't oppose a pull request that would make this work again.

**Comment by amirmohsen-am** [comment]
You were right, it is a 32-bit specific problem.
The code was compiled with python 2.7 32-bit correctly.

I actually looked at the C code for Python 2.7 and i saw some changes, and i assumed that's why i was having a problem.

Thanks for pointing out possible problems.
And I loved your presentations.

**Comment by brandon-rhodes** [comment]
Thank you! If you don't mind, I'm going to re-open this issue briefly to remind me to edit the project and have the code bail out with an error under 64 bits, so that no one else has to spend time confused by its failure. Thank you for re-trying and verifying the problem!
